name: h_m_coiffure
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/rectangle_haut.png
    - assets/images/rectangle_bas.png
    - assets/images/logo_hm.png
